BaseURL = "http://www.grainger.xyz"
relativeURLs = true
canonifyURLs = true
languageCode = "en-gb"
title = "Peter Grainger"
theme = "hugo-uno"
[indexes]
   category = "categories"
   tag = "tags"
[Params]
  AuthorName = "Peter Grainger"
  github = "theSmokingGnu"
  bitbucket = "peter_grainger"
  email = "petergrainger2000@gmail.com"
  description = "Random Coding Goodness"
  linkedin = "peterjamesgrainger"
  cover = "/images/background-cover.jpg"